### ISSUE TITLE
MCD: Move sets of functionality with side effects to clients to allow for unit testing

### ISSUE THREAD

**Issue by ashcrow** [openshift/machine-config-operator#101]
In https://github.com/openshift/machine-config-operator/pull/33 we identified that a major blocker for unittesting the MCD are all the side effects that occur from internal functions. The best way we came up with for getting around this limitation is to move things which cause side effects into clients. This issue is a tracker to link to as more of our items move over.

**Comment by cgwalters** [comment]
For rpm-ostree we end up not having a whole lot of unit tests and heavily lean on "integration tests" which inject the built code into a VM.   We're slowly adding some more unit tests since Rust makes it trivial but still...

I haven't hacked on this code really much myself yet, but I imagine we'd like to have a fairly fast iterative flow that tests something more "real" with live Ignition, rpm-ostree etc.

**Comment by runcom** [comment]
now that we have e2e properly setup, let's go e2e for these kinds of testing as the abstraction just adds complexity (and has some bug as well)
