### ISSUE TITLE
Need to create platform-specific namespaces only on that platform

### ISSUE THREAD

**Issue by cybertron** [openshift/machine-config-operator#1948]
See https://bugzilla.redhat.com/show_bug.cgi?id=1815561 for further background.

In short, the problem is that we are creating platform-specific namespaces (openshift-kni-infra, openshift-openstack-infra, etc.) even when installing on other platforms. From looking at how other operators are handling a similar situation, it seems like the way to handle this is to add some logic in https://github.com/openshift/machine-config-operator/blob/master/pkg/operator/sync.go that would be able to create the necessary namespace for only the platform in question. However, I wanted to open this to get input on the approach before I go too far down the path on the implementation. If there's somewhere else this should be handled please let me know. Thanks.

**Comment by kikisdeliveryservice** [comment]
Based on the post in the BZ this sounds bigger than a github issue and it sounds like this should be an enhancement so that interested parties can work this out and get on the same page:

 "Infra is a net new term in our namespace structure and so needs architectural review" &  "I also need to understand the use case."

**Comment by kikisdeliveryservice** [comment]
Discussion will be in : https://github.com/openshift/enhancements/pull/412/

So we get appropriate feedback from all interested parties. :smile_cat:

**Comment by kikisdeliveryservice** [comment]
closing in favor of enhancement
