### ISSUE TITLE
Add 10m Timeout for Node Informer

### ISSUE THREAD

**Issue by ashcrow** [openshift/machine-config-operator#207]
Per 2 in https://github.com/openshift/machine-config-operator/issues/199, lt's add a 10 minute timeout attempting to connect to the master for our informer. If we can't connect after 10 minutes we should assume something is wrong and go into degraded mode.

**Comment by yuqi-zhang** [comment]
With the fixes applied to https://github.com/openshift/machine-config-operator/pull/206, there is a 5min retry on a non-ready MC, and thus will no longer degrade before then. The error messages in the original issue is the informer starting correctly, and then realizing it cannot watch the (not ready) resource, and then trying repeatedly. I think currently the errors are handled here: https://github.com/kubernetes/client-go/blob/master/tools/cache/reflector.go#L134 which means that the informer itself (assuming the setup is successful) currently ALSO has a timeout of 5 minutes and will retry in that timeframe (and errors only log but do not cause degrades).

If that's correct I think the existing workflow should be ok since after 5 minutes the check in https://github.com/openshift/machine-config-operator/pull/206 will degrade anyways. I've tested that if the MC is ready within that 5 minute timeframe, updates are still detected and applied properly.

So maybe this issue can be instead be interpreted as "create a health check for the informer" so that if non-watch issues happen we can catch them and potentially restart the informer. But other parts of the MCC/MCO also use nodeInformer without health checks (e.g. https://github.com/openshift/machine-config-operator/blob/master/pkg/controller/node/node_controller.go and https://github.com/openshift/machine-config-operator/blob/master/cmd/machine-config-controller/start.go workflow)  so I'm not sure if it would make sense to create an overall one, or if that is too large in scope.

Maybe I'm interpreting this wrong, and help is appreciated.

**Comment by ashcrow** [comment]
I think we can actually close this since the issue is purely on the install path only, and a wait time has already merged. If we end up seeing issues with the  `Informer` degrading on errors which should be recoverable we should open up a new issue.

**Comment by jlebon** [comment]
> If that's correct I think the existing workflow should be ok since after 5 minutes the check in #206 will degrade anyways.

Just to clarify, the node informer is about watching for node updates. The timeout added in #206 is about watching for MachineConfig objects. So they're mostly independent of each other. E.g. it's possible that the MachineConfig objects are present and thus we don't degrade, but yet the node informer still keeps failing past the timeout, and we end up in a situation where we're unable to detect and apply updates (and thus *should* have gone into degraded mode).

That said, I don't know in practice if this is something folks are hitting. I don't think the logs in https://github.com/openshift/machine-config-operator/issues/199#issuecomment-443027774 is an example of the node informer timing out since it's clearly retrying, and then we reboot well before the 5 minutes are up. So I'm fine punting on this for now esp. since the same is true for the other components.

/close

**Comment by ashcrow** [comment]
Ah you're correct. It looks like the raw client gets used at that point. AFAICT no one is actually hitting this now that a bunch of flakes have been hit in the CI system.

/close
