### ISSUE TITLE
Add an "Unreconcilable" label distinct from degraded

### ISSUE THREAD

**Issue by cgwalters** [openshift/machine-config-operator#254]
Building on https://github.com/openshift/machine-config-operator/issues/234
First, we should never "reboot loop".

The two other outcomes today are (config updated successfully | degraded)

Now, what I want to argue is that we shouldn't go degraded if we can't reconcile a new config.  Going degraded is going to be expensive in some cases (particularly for masters).  An admin will want to *know* that e.g. the machineconfig they created is going to reprovision their entire cluster.

Let's introduce a distinct "unreconcilable" label.  If for example the admin messes up a machineconfig, they should totally have the option to just revert it and not degrade their machines.

IOW, degraded is *only* for the case where the node changed out from under us in an unexpected way, or some sort of fatal error (rpm-ostree isn't working, whatever).

Now, it may be that the admin *wants* to eat that reprovisioning; the MAO should also support reprovisioning unreconcilable systems too.  But let's distinguish those two cases.

Related: https://github.com/openshift/machine-config-operator/issues/234

**Comment by kikisdeliveryservice** [comment]
Adding a reminder to myself to add some thoughts to this since I use reconcilable a lot and have degraded so many nodes accidentally.

**Comment by jlebon** [comment]
Hmm, though if the MAO is going to reprovision degraded and unconcilable systems, then won't the admin be racing against the MAO either way?

It's also not clear to me how well we want to support admins creating their own MCs and risk the chance of blowing up their cluster vs a more validated path through the console or something.

**Comment by kikisdeliveryservice** [comment]
@jlebon makes a good point generally: how much of our varying workflows is consistent with the workflow of real admins/users? I think in the New Year it's worth hashing this out more because sometimes it's not clear how much of an issue things are in, say AWS vs libvirt, pinned vs master, or come up due to our unsupported-and-undesirable-for-users tinkering.  Thought of this bc @smarterclayton made a point of saying that we should be using (at least some of the time) AWS, etc.. and having a closer to real life user experience.

cc: @ashcrow @yuqi-zhang

**Comment by yuqi-zhang** [comment]
So is the proposed workflow then if we're in a unreconcilable state, sleep the node (but don't degrade) so the admin can be alerted and remove/apply a new MC? Should we maybe e.g. taint the node as well?

In terms of workflow for an admin, like @jlebon said I'm not sure how much we want an admin to create their own MC's that often, and whether the MAO would be trying to reprovision degrades. This might also cause more confusion since now there is a separate workflow for "unreconcilable" vs. "degraded".

Perhaps we should be detecting if a newly applied config is reconcilable before we apply the update, although could something go wrong during the update and it ended up being reconcilable somehow after the fact anyways? I think we should definitely hash this out a bit more if we want to add more complex state handing to the system.

**Comment by cgwalters** [comment]
One point Abhinav raised here is that currently we set `maxUnavailable: 1` - so you lose at most one machine.  But still...particularly if that affects a master...

**Comment by ashcrow** [comment]
We are supposed to be able to reject MC's if they are impossible to apply. Could we reject the MC instead?

**Comment by kikisdeliveryservice** [comment]
It seems more intuitive to reject the MC one it is deemed unreconcilable instead of marking the node as degraded, since we are just degrading it bc the MC is unreconcilable not because we tried to make the upgrade and it failed for some reason making the node unreconcilable.

**Comment by cgwalters** [comment]
One thing I just noticed is that `getDegradedMachines()` has
```if dconfig == currentConfig && dstate == daemon.MachineConfigDaemonStateDegraded {```

From the point of view of the MCC then a machine is only degraded if it's targeting that config.  Which strongly implies that the MCD should behave the same as much as possible - *particularly* if we fail to reconcile a config.  We can easily target a new config.

So rather than degrade() + sleep(), we just degrade but still react to `desiredConfig` changes.

But we still need a truly "fatal" degraded state when there are e.g. unexpected changes on disk or general unknown errors.

So I think my concrete proposal here is still to introduce an `unreconcilable` annotation that the MCD sets.  We would need to teach the MCC to bubble this up at a status level similarly to degraded, it's just not fatal.

**Comment by cgwalters** [comment]
If anyone is wondering how to deal with degraded nodes right now, there are two options.  

Removing the degraded state
---

 1. Remove the degraded annotation: For example, `oc edit nodes/osiris-worker-0-6x6fc` and change  `machineconfiguration.openshift.io/state: Degraded` to `machineconfiguration.openshift.io/state: Done`.
 1. Kill the MCD on the node; for example, `oc delete pods -l k8s-app=machine-config-daemon --field-selector spec.nodeName=osiris-worker-0-6x6fc`

Reprovisioning
---

The other option is to [delete the node](https://docs.openshift.com/container-platform/3.7/admin_guide/manage_nodes.html#deleting-nodes).  If your infrastructure is managed by the [machine API operator](https://github.com/openshift/machine-api-operator) (e.g. AWS), you'll also want to `oc -n openshift-cluster-api delete machines/osiris-worker-0-6x6fc`.

**Comment by ashcrow** [comment]
Thanks for adding that info @cgwalters!

FWIW `reprovisioning` is the generally expected route unless one is developing/debugging.

**Comment by jianlinliu** [comment]
> If anyone is wondering how to deal with degraded nodes right now, there are two options.
Here is my real-user scenarios, I make a messy MC, and apply it to my cluster, then some node go to "Degrade" state and sleep there. Before I follow the two suggested  option, first of all, I should remove the messy MC, right?

**Comment by ashcrow** [comment]
@jianlinliu That's correct. You'll want to revert back to a working MC otherwise the broken MC will continue to degrade hosts since the hosts can not apply the changes.

**Comment by runcom** [comment]
This is now a thing with #560
