### ISSUE TITLE
ootpa rebase fails due to SELinux `mac_admin`

### ISSUE THREAD

**Issue by cgwalters** [openshift/machine-config-operator#314]
```
Jan 15 21:51:42 osiris-worker-0-c2bsp kernel: type=1400 audit(1547589102.431:14): avc:  denied  { mac_admin } for  pid=56093 comm="pool" capability=33  scontext=system_u:system_r:spc_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=capability2 permissive=0
```

We have a special `install_exec_t` label for rpm-ostreed (see e.g. https://github.com/projectatomic/rpm-ostree/pull/953 https://github.com/projectatomic/rpm-ostree/pull/292#issue-71756967 )

But we're not using that because we're executing pivot from the MCD.  One option (I think) is to use `systemd-run` for pivot.  Downside is that the logs go to the journal, not the MCD, but we can scrape them?

EDIT: Actually the problem is:

```
I0115 21:55:07.102216   63098 run.go:14] Running: ostree pull-local srv/repo 9249e2dc8c0adf821ad4c43545900aa94b96216401a3d615799666454771dc03
error: Writing content object: fsetxattr: Invalid argument
```

So we're skipping rpm-ostreed.  Hmm.  Maybe the best would be to change pivot to add a `file:///` remote and then we rebase to it?    Another option is to explicitly set the exec context.

**Comment by cgwalters** [comment]
(This issue is an argument for rolling in at least some of the pivot functionality into rpm-ostreed itself)

**Comment by jlebon** [comment]
> EDIT: Actually the problem is:
>
> ```
>I0115 21:55:07.102216   63098 run.go:14] Running: ostree pull-local srv/repo 9249e2dc8c0adf821ad4c43545900aa94b96216401a3d615799666454771dc03
error: Writing content object: fsetxattr: Invalid argument
>```

I'm still confused why we're hitting this. `/usr/bin/ostree` is `install_exec_t` too, no?

**Comment by jlebon** [comment]
Ahh I see, it's not transitioning to `install_t` because we're invoking from a container.

>  Another option is to explicitly set the exec context.

If that works, that'd be my preference over https://github.com/projectatomic/rpm-ostree/pull/1732 given how specific the circumstances are.

**Comment by cgwalters** [comment]
> If that works, that'd be my preference over projectatomic/rpm-ostree#1732 given how specific the circumstances are.

In order to make it work we'd have to mount `selinuxfs`...which would then cause other tools in the container to think SELinux is enabled, which *probably* wouldn't be a problem but still...an unknown impact.

I think it's going to work best if we do SELinux related things on the host and keep our container more container-like.

And more generally...I think we want to keep the model of having "host APIs" that live on the host where that makes sense, and the MCD drives them.

**Comment by jlebon** [comment]
> I think we want to keep the model of having "host APIs" that live on the host where that makes sense, and the MCD drives them

Yeah that makes sense. This is also the root of the issue here. We're calling the host `pivot` from the container context. Hmm, how about something like this:

`rhcos-pivot.path`

```
[Unit]
Description=Pivot Tool
Documentation=man:ostree(1)

[Path]
PathExists=/run/pivot/foobar
```

`rhcos-pivot.service`
```
...
[Service]
ExecStart=/usr/bin/pivot --from-file /run/pivot/foobar
```

?

**Comment by cgwalters** [comment]
Which we want anyways, see https://github.com/openshift/machine-config-operator/pull/273/commits/94d37831db7f6e2ea95d6d808f6406fde6aa79db

**Comment by jlebon** [comment]
So, was playing around with an ootpa rebase now with https://github.com/openshift/pivot/pull/25 and https://github.com/openshift/machine-config-operator/pull/335, I see:

```
Jan 31 15:55:45 test1-worker-0-52h47 pivot[15178]: I0131 15:55:45.966042   15178 run.go:15] Running: ostree pull-local srv/repo 862a286d84c486f9accae3af5354389e4f9bfebdfb559392b537ff4cddbd244f
Jan 31 15:55:50 test1-worker-0-52h47 kernel: type=1400 audit(1548950150.854:391): avc:  denied  { mac_admin } for  pid=15303 comm="pool" capability=33  scontext=system_u:system_r:unconfined_service_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=capability2 permissive=0
```

I.e. `pivot` no longer runs as `spc_t`, which is nice. But it runs as the generic `unconfined_service_t` (see [this blog post for more info](https://danwalsh.livejournal.com/70577.html)). It then executes `ostree` which just inherits `unconfined_service_t` (IIUC, the transition to `install_t` only happens if it's launched by `unconfined_t` (e.g. shell prompt) or `init_t` (i.e. systemd)).

I also played with making pivot do `runcon -t install_t ostree pull-local ...` but `unconfined_service_t` is not allowed to transition to `install_t`:

```
Jan 31 15:58:37 test1-worker-0-52h47 pivot[16401]: I0131 15:58:37.046269   16401 run.go:15] Running: runcon -t install_t ostree pull-local srv/repo 862a286d84c486f9accae3af5354389e4f9bfebdfb559392b537ff4cddbd244f
Jan 31 15:58:37 test1-worker-0-52h47 kernel: type=1400 audit(1548950317.050:400): avc:  denied  { transition } for  pid=16545 comm="runcon" path="/usr/bin/ostree" dev="vda2" ino=17042980 scontext=system_u:system_r:unconfined_service_t:s0 tcontext=system_u:system_r:install_t:s0 tclass=process permissive=0
```

So, a few choices here:
1. Tweak SELinux policy to label `/usr/bin/pivot` as `install_exec_t`. We don't have to modify the distro policy for this; we can just ship a tiny pp with the package (we do this today in the rpm-ostree vmcheck testsuite).
2. Teach rpm-ostree to do the pull-local and rebase (essentially like https://github.com/projectatomic/rpm-ostree/pull/1732, but we still also run pivot from the host to keep a clear separation).

I'm leaning more towards the latter now, though the former wouldn't be too hard either and would probably require less churn.

**Comment by cgwalters** [comment]
I think 2. is probably best.  A bit more work/risk but also cleanest.
