### ISSUE TITLE
oc debug defeats the accessed annotation

### ISSUE THREAD

**Issue by runcom** [openshift/machine-config-operator#433]
**Description**

running `oc debug node/nodename` effectively gives access to a node defeating our access checks to mark a node as accessed

**Steps to reproduce the issue:**
1. `oc debug node/nodename`
2. from within the debug pod `chroot /host /bin/bash`
3.

**Describe the results you received:**

access to a node through a pod with zero awareness from the MCD

**Describe the results you expected:**

ssh/accessed-like annotation added to the node to inform the MCD someone might have screwed the host

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `oc adm release info --commits | grep machine-config-operator`:**

```
any version with a recent oc binary which has the debug command
```

**Additional environment details (platform, options, etc.):**

**Comment by kikisdeliveryservice** [comment]
Q: should this get the same accessed notation as someone sshing in? Or some different notation?

Related: https://github.com/openshift/origin/pull/21997

**Comment by runcom** [comment]
> Q: should this get the same accessed notation as someone sshing in? Or some different notation?

right, I'm leaning towards answering yes to that

**Comment by cgwalters** [comment]
Keep in mind that `oc debug node` is just sugar; a kubeadmin can schedule any privileged container that mounts the host.

It'd be much more reliable to detect any containers that do both of those things in the kubelet e.g.

(Perhaps even more generally any privileged containers from outside of the platform - since if you have `CAP_SYS_ADMIN` you can easily do whatever you want even from inside a mount namespace, including dynamically mount in the host or load kernel modules or...)

**Comment by yuqi-zhang** [comment]
Alternatively, would it make sense for the MCD to periodically check the host for drifts from expected state that would "screw up" the node? 

Also with https://github.com/openshift/installer/pull/1045 merged it's unlikely we'll see many SSH access's in general.

**Comment by runcom** [comment]
> Alternatively, would it make sense for the MCD to periodically check the host for drifts from expected state that would "screw up" the node?

Yeah, I believe this has been discussed already somewhere and looks sane as well
