### ISSUE TITLE
Expose API for blocking and initiating reboots

### ISSUE THREAD

**Issue by cgwalters** [openshift/machine-config-operator#662]
We have multiple requests for a way for external components to initiate the drain+reboot.  Other software *can* do this but if it's not coordinated with the MCO problems will arise.

We face a tension for whether some of this functionality should be part of the MCO itself, but anyways here's a strawman:

`/run/machine-config-operator/rebooting` is a flag file the MCO writes when it starts a drain+reboot.

`/run/machine-config-operator/reboot-lock.d/`
is a directory, and a component can do e.g.:
`echo preparing new kernel module > /run/machine-config-operator/reboot-lock.d/nvidia`

As long as at least 1 entry exists, the MCO will not initiate a drain + reboot.  However in order to avoid a race condition, external components must check if `/run/machine-config-operator/rebooting` exists after they wrote a lock file - if it does, they lost a race and should not attempt any host modifications.

`/run/machine-config-operator/reboot-start.d/`

When the app has completed its preparation, it does:
`mv /run/machine-config-operator/reboot-{lock,start}.d/nvidia`

And the MCD will start a drain+reboot when there is at least 1 entry in `.start.d` and no locks.

**Comment by pliurh** [comment]
I have a use case for this API. Now we are working on an operator which can setup the SRIOV NIC on baremetal hosts. We plan to support NICs from Intel and Mellanox. 

However, for Mellanox NICs, to enable the SRIOV and set the max number of VFs, it requires to use 'mstconfig' tool to configure the firmware, then to reboot the node to take effect[1]. So we would like to have this API so that rebooting can be better coordinated among the cluster. So that we don't need to implement the drain+reboot logic in our own daemon.
 
[1]https://access.redhat.com/articles/3082811

**Comment by jeremyeder** [comment]
The tuned use-case for needing to trigger reboots is when tuned adds kernel command line options that are part of a tuned profile.  Several discussions occurred with the perf team and MCO team over the last 6 months about ensuring tunings delivered via tuned are clearly & cleanly coordinated with the MCO and MCD.

/cc @runcom @jmencak

**Comment by cgwalters** [comment]
> The tuned use-case for needing to trigger reboots is when tuned adds kernel command line options that are part of a tuned profile.

I really rather strongly think only the MCO should be writing kernel arguments.  See https://github.com/openshift/machine-config-operator/issues/388

**Comment by pliurh** [comment]
@cgwalters #388 is for RHCOS only, right? What is the plan for BYOH case?

**Comment by cgwalters** [comment]
I was thinking more about this recently and I think there are even cases where we want this inside the MCO itself effectively.

This is related to work on [early kargs](https://github.com/openshift/machine-config-operator/issues/798) but it's really generic to the situation where the MCD detects "drift" from the desired state.  In that case if the MCD wants to reconcile, it needs to coordinate with the node controller by requesting a reboot.

**Comment by cgwalters** [comment]
> @cgwalters #388 is for RHCOS only, right? What is the plan for BYOH case?

Sorry I didn't follow up on this.  I think the general consensus is that we shouldn't try to get the MCO too much into the "grey area" of "we'll partially manage this node".  So if we had this API it would allow e.g. someone to use Puppet/Ansible or whatever on a traditional RHEL system and change kargs, then request a reboot coordinating with the MCO.

**Comment by cgwalters** [comment]
OK let me straw man out a simplistic version of this.

If `/run/machine-config-operator-reboot` exists, the MCD will add a `machineconfiguration.openshift.io/reboot-requested` annotation.  The node controller will create a `machineconfiguration.openshift.io/reboot-approved` annotation on at most one node at a time.

This would happen even for MCO-initiated upgrades; today, the controller setting `desiredConfig` is implicitly taken by the MCD as permission to reboot.  

Probably, the controller should for now set `reboot-approved` *and* `desiredConfig` at the same time.  But you could imagine that e.g. semantics for `desiredConfig` but *not* `reboot-approved` is that we try to "prepare" for an update..e.g. we can pull the oscontainer at least.

Anyways, the MCD would react to having both `reboot-requested` and `reboot-approved` as permission to drain+reboot.

If `reboot-requested` exists but the file in `/run` doesn't, the MCD would simply delete both annotations (if they exist) and not reboot. 

This version of the proposal doesn't have any locking; we can add that later.

**Comment by cgwalters** [comment]
Side note...it sure seems like `kebab-case` is the most prevalent for *values* such as container names, annotations and labels etc., and `currentConfig` and `desiredConfig` should really be `current-config` and `desired-config`...

**Comment by cgwalters** [comment]
Aaah now that I look e.g. this `Node` object has 

```
labels:
    node.openshift.io/os_version: "4.1"
    ...
spec:
  providerID: aws:///us-east-2a/i-059faef34eb25024b
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
```

Which includes camelCase, PascalCase, kebab-case, *and* snake_case (which seems to be our fault).  Anyways I can't unsee it send help

**Comment by cgwalters** [comment]
PR for this in https://github.com/openshift/machine-config-operator/pull/926

**Comment by runcom** [comment]
To add on the Ceph storage requirements, their scenario is as follows:

- upgrade (or config change is initiated)
- despite the maxUnavailable set for a pool, the storage operator has an additional requirement to avoid draining+rebooting the _next_ node unless the previous being updated is healthy && the ceph cluster becomes healthy as well
- the above means there must be something which _controls_ the upgrade/config change steps

This issue/proposal looks like it could solve the issue above, by providing an API for external component to _control_ whether to go ahead and drain+reboot a node (this is limited to reboot right?).

**Comment by rohantmp** [comment]
Yup, that description of the ceph use case is accurate!

**Comment by cgwalters** [comment]
OK, currently our definition of "healthy" is "kubelet is up and MCD running".  If we had a mechanism for other pods or daemonsets to register with us and block completion, that seems like it'd be sufficient right?

I guess one example here is - until the SDN pod lands in practice no other workloads are going to function - should the MCO know about this and avoid starting to drain other nodes until SDN is up?

Hmm.  Are these ceph pods pinned to nodes?  For example they are using a raw block device attached to the machine?

**Comment by runcom** [comment]
> OK, currently our definition of "healthy" is "kubelet is up and MCD running". If we had a mechanism for other pods or daemonsets to register with us and block completion, that seems like it'd be sufficient right?

this is indeed super helpful - I thought about that above being driven by annotation but maybe you have another idea? The issue here could be "who removes the "hold" annotation" probably

**Comment by rohantmp** [comment]
> OK, currently our definition of "healthy" is "kubelet is up and MCD running".

For our requirement, it's ceph cluster reports healthy.

>  If we had a mechanism for other pods or daemonsets to register with us and block completion, that seems like it'd be sufficient right?

If by completion, you mean proceeding with any reboots, then yeah. Making the reasonable assumption that we can block before you proceed to the next node.

> 

> Hmm. Are these ceph pods pinned to nodes? For example they are using a raw block device attached to the machine?

In baremetal environments they would be.

**Comment by runcom** [comment]
> this is indeed super helpful - I thought about that above being driven by annotation but maybe you have another idea? The issue here could be "who removes the "hold" annotation" probably

the trigger for the ceph cluster would also be:

- first node is updated
- meanwhile, ceph operator witness that ceph is unhealthy and put an hold on the node (or should be this be the pool?)
- MCO/MCC holds
- ceph becomes ready again
- MCO/MCC proceeds
- unhealthy again
- repeat from step 3

This could be expanded to SDN also right?

**Comment by rohantmp** [comment]
Yup
> meanwhile, ceph operator witness that ceph is unhealthy and put an hold on the node (or should be this be the pool?)

For ceph, we would prefer pool. I guess we can annotate all the nodes we use to achieve the same effect while also leaving out the nodes that ceph is not running on.

Note: we will require a maxUnavailable of 1.

**Comment by runcom** [comment]
> Note: we will require a maxUnavailable of 1 for this to be effective.

as discussed, there's already an API to change that (the MachineConfigPool CRD)

**Comment by cgwalters** [comment]
Another high level question for ceph: I think I saw the operator today is trying to integrate with machine/cluster API to ensure (underlying machines don't go away?  or something?), is that a requirement *in addition* to this?  Or if we had a better linkup between the MCO and machine API would it work to just rely on hooking into the MCO?

**Comment by rohantmp** [comment]
> Another high level question for ceph: I think I saw the operator today is trying to integrate with machine/cluster API to ensure (underlying machines don't go away? or something?), is that a requirement in addition to this?

Yup, [MachineHealthCheck](https://github.com/openshift/machine-api-operator#machine-healthcheck-controller) deletes Machines when they meet certain conditions: `NotReady` for 5 minutes, etc.

> Or if we had a better linkup between the MCO and machine API would it work to just rely on hooking into the MCO?

It would be great if:
- both used the same system
- budgets (maxUnavailable) could be generalized to refer to failure domains instead of just nodes
- had plugin system that could be hooked to check when a HA infrastructure application is in a state where it can take disruption. (like a liveliness check)

**Comment by cgwalters** [comment]
> budgets (maxUnavailable) could be generalized to refer to failure domains instead of just nodes

This is a big topic...one I think we do need to tackle in the MCO, as it's not just ceph that needs this I believe.  For example the router today wants to run in multiple AZs.

It's an interesting question - for people who set `maxUnavailable > 1`...would they prefer faster upgrades (e.g. we evict multiple router pods) or should we maintain availability constraints?

**Comment by runcom** [comment]
was playing around with a potential API for Ceph until I realized a mix of MaxUnavailable and Paused on the MCP can do the trick just fine. When Ceph realizes we need to wait for Ceph to become available again, they can set Paused on the pool and skips nodes annotations. Will play with that again to further verify it.

**Comment by runcom** [comment]
alrighty, it seems to be working by using Paused - the only downside to that is that there could be multiple users of the same field but I'm leaning towards deferring a proper API at this point (short on time), thoughts?

**Comment by runcom** [comment]
I'm also playing with an "hold" annotation driven mechanism where we can actually expose as a counter so N external components can interact with it.

**Comment by rohantmp** [comment]
I understand that we're going towards a proper API, but where can I find more info on "Paused"?

**Comment by runcom** [comment]
> I understand that we're going towards a proper API, but where can I find more info on "Paused"?

Paused can be a stopgap I guess - probably better to check https://github.com/openshift/machine-config-operator/pull/974 instead to avoid messing up with real admins setting Paused (?)

**Comment by jmencak** [comment]
> > The tuned use-case for needing to trigger reboots is when tuned adds kernel command line options that are part of a tuned profile.
> 
> I really rather strongly think only the MCO should be writing kernel arguments. See #388

If only MCO should be writing "kernel arguments"/bootloader config, is there any plan to support this on RHEL7/8 hosts too?  The functionality is needed by other operators and some are already [taking matters into their hands](https://github.com/openshift/sriov-network-operator/pull/46).

**Comment by mhrivnak** [comment]
I'll describe some problems from the KNI perspective, which includes ceph on bare metal hyperconverged (running on all nodes, including masters).

MachineConfigPools are not a useful boundary for preserving availability. While we configure masters and workers differently, we need something like `MaxUnavailable` to apply across all machines because relevant workloads like ceph run across all machines.

Node readiness is not the best metric for availability. In the course of recovering from a failure, a Node may be deleted and replaced. From an availability perspective, the Node's absence may be just as significant as its lack of readiness. It would be a shame for it to no longer be counted in the unavailability calculation after it gets deleted. It would be better to use something like the cluster-api's MachineSet to know how many Machines and Nodes should exist vs. do exist.

The "paused" feature might help, but something will need to actively manage it. We have at least two reasons so far to pause a pool: 1) only one pool at a time can be un-paused, because we can't have two nodes taken down at the same time even if they're in different pools. 2) we would need to pause all pools any time ceph is unhealthy.

Perhaps the MachineConfigPool is not the best place to express availability limits. Something like the [MachineDisruptionBudget](https://github.com/kubevirt/machine-remediation-operator/blob/a5947c2/docs/machine-disruption-budget.md) could be a better choice. Of course that would require MCO to integrate with the cluster-api, but that could have a lot of advantages. Is there a particular design argument for why these limits should be expressed on the MachineConfigPool? Or was that a matter of not having sufficient reason at the time to put it somewhere else?

Ultimately it's hard to express the kind of availability constraints that ceph has through any of MachineConfigPools, PodDisruptionBudgets, or MachineDisruptionBudgets.

Potentially helpful docs from rook:
* [MachineDisruptionBudgets used for fencing](https://github.com/rook/rook/blob/3abadd05719f6fcc45cea568744c0e030614e26a/design/ceph-openshift-fencing-mitigation.md)
* [managed PodDisruptionBudgets](https://github.com/rook/rook/blob/46ca00627fe99a1e42f2dd5b6844e8b679f017f0/design/ceph-managed-disruptionbudgets.md)

@beekhof FYI

**Comment by beekhof** [comment]
MCO drains prior to rebooting nodes, however on bare metal there is much more value in triage and repair of problems - so we're interested in something that just does drain.
As discussed on aos-devel, MCO's co-operative reboot mechanism isn't usable for fencing/remediation because we've lost the ability to communicate with it.  However it would be desirable for MCO and machine health check to respect the same "leave this node alone" mechanism/annotation.
